
#模型配置（可同时加载多个模型）
MODEL:
  DEVICE: "0"
  TYPES:  # 不同种类的模型
    MAN:
      WEIGHTS: "./weights/man.pt"
      DEVICE: "0"
    
#摄像机配置（可同时读取多个摄像头）
CAMERA:
  FPS: 20 #每秒读取图片数
  DEVICES:
    '摄像头1':
      IP: "192.168.0.25"
      NAME: "admin"
      PWD: "iic309311"
      PORT: 554
      MODEL_TYPES: ["man"]
      RTMP/RTSP: "rtmp://127.0.0.1:1935/man/test1"
